version: "3.8"

services:
  db:
    image: postgres:16-alpine
    container_name: unimind-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '123!@#'
      POSTGRES_DB: unimind
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - unimind-network
    restart: always

  qdrant:
    image: qdrant/qdrant:latest
    container_name: unimind-qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - unimind-network
    restart: always

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: unimind-backend
    ports:
      - "2025:2025"
    depends_on:
      - db
      - qdrant
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - unimind-network
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=http://localhost:2025
        - VITE_API_PREFIX=/api/v1
    container_name: unimind-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - unimind-network
    restart: always

volumes:
  postgres_data:
  qdrant_data:
  ollama_data:

networks:
  unimind-network:
    driver: bridge
